.PHONY: clean All

All:
	@echo "----------Building project:[ Throttle - Debug ]----------"
	@cd "Throttle" && "$(MAKE)" -f  "Throttle.mk"
clean:
	@echo "----------Cleaning project:[ Throttle - Debug ]----------"
	@cd "Throttle" && "$(MAKE)" -f  "Throttle.mk" clean
