.PHONY: clean All

All:
	@echo "----------Building project:[ Node2 - Debug ]----------"
	@cd "Node2" && "$(MAKE)" -f  "Node2.mk"
clean:
	@echo "----------Cleaning project:[ Node2 - Debug ]----------"
	@cd "Node2" && "$(MAKE)" -f  "Node2.mk" clean
