.PHONY: clean All

All:
	@echo "----------Building project:[ Node - Debug ]----------"
	@cd "Node" && "$(MAKE)" -f  "Node.mk"
clean:
	@echo "----------Cleaning project:[ Node - Debug ]----------"
	@cd "Node" && "$(MAKE)" -f  "Node.mk" clean
